//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int id_answer { get; set; }
        public int question_id { get; set; }
        public string answer_text { get; set; }
        public bool is_correct { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
